import { Injectable, Logger } from '@nestjs/common';
import type { ContentTopic } from '@spa/shared';
import { PrismaService } from '../prisma/prisma.service';

/**
 * DB-backed content reader — implements IContentPort using the Topic table.
 * Replaces ContentReader (which reads from the CAP sibling repo filesystem)
 * so the app no longer depends on content-agent-platform being present.
 *
 * Topics are generated by TopicGenerationService (LLM cron) and stored in DB.
 * This reader fetches active, unused topics ordered by freshness.
 */
@Injectable()
export class DbContentReader {
  private readonly logger = new Logger(DbContentReader.name);

  constructor(private readonly prisma: PrismaService) {}

  async getTopics(limit = 5): Promise<ContentTopic[]> {
    try {
      const rows = await this.prisma.topic.findMany({
        where: { status: 'active' },
        orderBy: [{ createdAt: 'desc' }],
        take: limit,
      });

      const topics: ContentTopic[] = rows.map((r) => ({
        sourceType: 'brief',
        path: `db:${r.id}`,
        topic: r.topic,
        keywords: (r.keywords as string[]) ?? [],
        facts: (r.facts as string[]) ?? [],
        category: r.category ?? 'general',
        publishedAt: r.createdAt,
      }));

      this.logger.log(`DB content reader: ${topics.length} topics from DB`);
      return topics;
    } catch (err) {
      this.logger.warn(`DB content reader failed: ${(err as Error).message}`);
      return [];
    }
  }

  async readBriefs(limit = 10): Promise<ContentTopic[]> {
    // In DB mode, all topics are equivalent — return same set
    return this.getTopics(limit);
  }

  async readArticles(limit = 10): Promise<ContentTopic[]> {
    return this.getTopics(limit);
  }

  /**
   * Mark a topic as used (so it's not repeated in the next generation cycle).
   */
  async markUsed(topicId: string): Promise<void> {
    const id = topicId.startsWith('db:') ? topicId.slice(3) : topicId;
    await this.prisma.topic.update({
      where: { id },
      data: { status: 'used', usedAt: new Date() },
    }).catch((err) => {
      this.logger.debug(`Failed to mark topic ${id} as used: ${err.message}`);
    });
  }

  /**
   * Count active topics remaining in the pool.
   */
  async activeCount(): Promise<number> {
    return this.prisma.topic.count({ where: { status: 'active' } });
  }
}
