import { Injectable, Logger } from "@nestjs/common";
import type { ContentTopic } from "@spa/shared";
import { PrismaService } from "../prisma/prisma.service";
import type { IContentAdapter } from "./adapters/content-adapter.interface.js";

/**
 * DB-backed content reader — implements IContentAdapter using the Topic table.
 * Replaces ContentReader (which reads from the CAP sibling repo filesystem)
 * so the app no longer depends on content-agent-platform being present.
 *
 * Topics are generated by TopicGenerationService (LLM cron) and stored in DB.
 * This reader fetches active, unused topics ordered by freshness.
 */
@Injectable()
export class DbContentReader implements IContentAdapter {
  readonly sourceType = "db";
  lastError: string | null = null;

  private readonly logger = new Logger(DbContentReader.name);

  constructor(private readonly prisma: PrismaService) {}

  async getTopics(limit = 5): Promise<ContentTopic[]> {
    try {
      const rows = await this.prisma.topic.findMany({
        where: { status: "active" },
        orderBy: [{ createdAt: "desc" }],
        take: Number(limit) || 5,
      });

      const topics: ContentTopic[] = rows.map((r) => ({
        sourceType: "brief",
        path: `db:${r.id}`,
        topic: r.topic,
        keywords: (r.keywords as string[]) ?? [],
        facts: (r.facts as string[]) ?? [],
        category: r.category ?? "general",
        publishedAt: r.createdAt,
        language: "en",
      }));

      this.logger.log(`DB content reader: ${topics.length} topics from DB`);
      return topics;
    } catch (err) {
      this.logger.warn(`DB content reader failed: ${(err as Error).message}`);
      return [];
    }
  }

  async readBriefs(limit = 10): Promise<ContentTopic[]> {
    // In DB mode, all topics are equivalent — return same set
    return this.getTopics(limit);
  }

  async readArticles(_limit = 10): Promise<ContentTopic[]> {
    // DB topics are brief-style, not full articles.
    return [];
  }

  /**
   * 2.8.1: Mark a topic as used (so it's not repeated in the next generation cycle).
   */
  async markUsed(topic: ContentTopic): Promise<void> {
    const topicId = topic.path;
    if (!topicId.startsWith("db:")) {
      // Not a DB-backed topic (e.g. synthetic recycle topic) — nothing to mark.
      return;
    }
    const id = topicId.slice(3);
    await this.prisma.topic
      .update({
        where: { id },
        data: { status: "used", usedAt: new Date() },
      })
      .catch((err) => {
        this.logger.debug(`Failed to mark topic ${id} as used: ${err.message}`);
      });
  }

  /**
   * Count active topics remaining in the pool.
   */
  async activeCount(): Promise<number> {
    return this.prisma.topic.count({ where: { status: "active" } });
  }

  canHandle(sourceType: string): boolean {
    return sourceType === "brief";
  }

  async fetchTopics(limit = 5, since?: Date): Promise<ContentTopic[]> {
    const topics = await this.getTopics(limit);
    return since ? topics.filter((t) => t.publishedAt && t.publishedAt >= since) : topics;
  }

  async healthCheck(): Promise<{ ok: boolean; error?: string }> {
    try {
      await this.prisma.topic.count({ where: { status: "active" } });
      return { ok: true };
    } catch (err) {
      this.lastError = (err as Error).message;
      return { ok: false, error: this.lastError };
    }
  }
}
